name: "[Case:prj.5020.be.base] Publish Latest - Watch"

on:
  workflow_dispatch:

jobs:
  prepare-values:
    runs-on: ubuntu-latest
    steps:
      -
        name: "[JOB] Start"
        run:  echo "start."
